### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by visze** [kircherlab/negative_training_sampler#3]
To short issues that are missing/wrong in the README:

- After installing `pip install /path/to/repo`you have to reastart the shell. otherwise the command `negative_training_sampler` is not available
- README writes `python negative_training_sampler --help`. I think the command is without `python`

**Comment by sroener** [comment]
> After installing pip install /path/to/repoyou have to reastart the shell. otherwise the command negative_training_sampler is not available

I tried this on multiple machines and I can't reproduce this problem. For me the package is directly available.

> README writes python negative_training_sampler --help. I think the command is without python

Kind of true. If the package is executed without installation via pip, the command is preceded by the `python` command to invoke the interpreter. I fixed it in the README and make a separate in future, more expanded documentation.
